{
 "title": "Lotto",
 "time": { "from": "now/y", "to": "now/y" },
 "panels": [
  {
   "title": "로또 1등 금액 추이",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  drwNoDate as \"Time\",\r\n  --drwNo,\r\n  --firstPrzwnerCo,\r\n  firstWinamnt as \"당첨금액\"\r\n  -- drwtNo1,\r\n  -- drwtNo2,\r\n  -- drwtNo3,\r\n  -- drwtNo4,\r\n  -- drwtNo5,\r\n  -- drwtNo6,\r\n  -- bnusNo\r\nFROM\r\n  lotto\r\n--WHERE Time in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "최근 1등 당첨자",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n -- drwNoDate as \"Time\",\r\n  --drwNo,\r\n  firstPrzwnerCo as \"1등 당첨자 수\"\r\n  --firstWinamnt\r\n  -- drwtNo1,\r\n  -- drwtNo2,\r\n  -- drwtNo3,\r\n  -- drwtNo4,\r\n  -- drwtNo5,\r\n  -- drwtNo6,\r\n  -- bnusNo\r\nFROM\r\n  lotto\r\n--WHERE Time in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "로또 1등 당첨자 추이",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  drwNoDate as \"Time\",\r\n  --drwNo,\r\n  firstPrzwnerCo as \"1등 당첨자 수\"\r\n  --firstWinamnt\r\n  -- drwtNo1,\r\n  -- drwtNo2,\r\n  -- drwtNo3,\r\n  -- drwtNo4,\r\n  -- drwtNo5,\r\n  -- drwtNo6,\r\n  -- bnusNo\r\nFROM\r\n  lotto\r\n--WHERE Time in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "로또 1등 금액 추이",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  drwNoDate as \"Time\",\r\n  drwNo as \"회차\",\r\n  --firstPrzwnerCo,\r\n  --firstWinamnt as \"당첨금액\"\r\n   drwtNo1 as \"NO1\",\r\n   drwtNo2 as \"NO2\",\r\n   drwtNo3 as \"NO3\",\r\n   drwtNo4 as \"NO4\",\r\n   drwtNo5 as \"NO5\",\r\n   drwtNo6 as \"NO6\",\r\n   bnusNo as \"보너스\"\r\nFROM\r\n  lotto\r\n--WHERE Time in ($year) AND name in ($exercise_sort);"
    }
   ]
  }
 ]
}