{
 "title": "exercise",
 "time": { "from": "now-60d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "year",
    "label": "날짜",
    "query": "select to_char(year, 'yyyy-mm-dd') from exercise ;"
   },
   { "name": "exercise_sort", "label": "운동 종류", "query": "select name from exercise" },
   {
    "name": "year1",
    "label": "날짜(홈)",
    "query": "select to_char(year, 'yyyy-mm-dd') from home_exercise ;"
   },
   { "name": "exercise_sort1", "label": "운동 종류(홈)", "query": "select name from home_exercise" }
  ]
 },
 "panels": [
  {
   "title": "운동 데이터",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute,\r\n  distance,\r\n  calories\r\nFROM\r\n  exercise\r\nWHERE year in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "운동 데이터",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute,\r\n  distance,\r\n  calories\r\nFROM\r\n  exercise\r\nWHERE year in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "운동 일 수",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(year)) as Count from exercise;"
    }
   ]
  },
  {
   "title": "기울기 런닝머신",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute,\r\n  distance,\r\n  calories\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ('기울기 런닝머신');"
    }
   ]
  },
  {
   "title": "기울기 런닝머신 Calories",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  calories\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ('기울기 런닝머신');"
    }
   ]
  },
  {
   "title": "기울기 런닝머신km",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  distance\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ('기울기 런닝머신');"
    }
   ]
  },
  {
   "title": "런닝머신 ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute,\r\n  distance,\r\n  calories\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ('런닝머신');"
    }
   ]
  },
  {
   "title": "런닝머신 Calories",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  calories\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ('런닝머신');"
    }
   ]
  },
  {
   "title": "런닝머신 km",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  distance\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ('런닝머신');"
    }
   ]
  },
  {
   "title": "home 운동 데이터",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute,\r\n  count_m\r\nFROM\r\n  home_exercise\r\nWHERE year in ($year1) AND name in ($exercise_sort1);"
    }
   ]
  },
  {
   "title": "home 운동 데이터",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute,\r\n  count_m\r\nFROM\r\n  home_exercise\r\nWHERE year in ($year1) AND name in ($exercise_sort1);"
    }
   ]
  },
  {
   "title": "home 운동 일 수",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(year)) as Count from home_exercise;"
    }
   ]
  },
  {
   "title": "운동 데이터",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute as \"exercise\"\r\nFROM\r\n  exercise\r\nWHERE year in ($year) AND name in ($exercise_sort)\r\norder by year;"
    },
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute as \"home_exercise\"\r\nFROM\r\n  home_exercise\r\nWHERE year in ($year1) AND name in ($exercise_sort1)\r\norder by year;"
    }
   ]
  },
  {
   "title": "총 운동 일 수",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(he.year))+count(distinct(e.year)) as Count from home_exercise he, exercise e;"
    }
   ]
  }
 ]
}