{
 "title": "exercise",
 "time": { "from": "2021-12-31T15:00:00.000Z", "to": "2022-12-31T14:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "year",
    "label": "날짜",
    "query": "select to_char(year, 'yyyy-mm-dd') from exercise"
   },
   { "name": "exercise_sort", "label": "운동 종류", "query": "select name from exercise" }
  ]
 },
 "panels": [
  {
   "title": "운동 데이터",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute,\r\n  distance,\r\n  calories\r\nFROM\r\n  exercise\r\nWHERE year in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "운동 일 수",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*)/2 as Count from exercise;"
    }
   ]
  },
  {
   "title": "런닝머신 ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute,\r\n  distance,\r\n  calories\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ('런닝머신');"
    }
   ]
  },
  {
   "title": "런닝머신 Calories",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  calories\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ('런닝머신');"
    }
   ]
  },
  {
   "title": "기울기 런닝머신",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute,\r\n  distance,\r\n  calories\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ('기울기 런닝머신');"
    }
   ]
  },
  {
   "title": "기울기 런닝머신 Calories",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  calories\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ('기울기 런닝머신');"
    }
   ]
  },
  {
   "title": "런닝머신 km",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  distance\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ('런닝머신');"
    }
   ]
  },
  {
   "title": "기울기 런닝머신km",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  distance\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ('기울기 런닝머신');"
    }
   ]
  }
 ]
}