{
 "title": "운동대시보드2",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   {
    "name": "year",
    "label": "날짜",
    "query": "select to_char(exercise.year, 'yyyy-mm-dd') as year from  exercise \nunion all\nselect to_char(home_exercise.year, 'yyyy-mm-dd')as year from  home_exercise\norder by year DESC\n;"
   },
   {
    "name": "exercise_sort",
    "label": "운동 종류(홈)",
    "query": "select name from home_exercise where year in ($year)\n union all\nselect name from exercise where year in ($year)\n"
   }
  ]
 },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 } },
  { "title": "목표 운동 게이지", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "플랭크 100분 달성 게이지",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select name, ((sum(minute)/60)/100)*100 as 분 from home_exercise where name in ('Elbow plank') group by name, minute "
    }
   ]
  },
  {
   "title": "플랭크 트위스트 100분 달성 게이지",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select name, sum(minute)/60 as 초 from home_exercise where name in ('Plank twist') group by name, minute "
    }
   ]
  },
  {
   "title": "운동 데이터 분단위 (%)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(year), name, minute/ 60  as \" \"  from home_exercise;"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select name, sum(minute)/60 as 초 from home_exercise where name in ('Elbow plank') group by name, minute "
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select name, sum(minute)/60 as 초 from home_exercise where name in ('Plank twist') group by name, minute "
    }
   ]
  },
  {
   "title": "운동 데이터 분단위 (히스토그램)",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select $__time(year), name, minute/ 60  as \" \"  from home_exercise;"
    }
   ]
  },
  {
   "title": "운동 데이터  횟수 단위 (히스토그램)",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "rawSql": "select $__time(year), name, count_m  as \" \"  from home_exercise;"
    }
   ]
  },
  {
   "title": "운동 데이터 분단위 (%)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(year), name, count_m  as \" \"  from home_exercise;"
    }
   ]
  },
  { "title": "운동영상", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "체지방 녹이는 루틴 15븐 영상",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 20 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "first",
      "firstNotNull",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   }
  },
  {
   "title": "체지방 녹이는 루틴 15븐 영상",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 20 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "first",
      "firstNotNull",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   }
  },
  {
   "title": "11자 복근만드는 동영상",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 11, "w": 5, "x": 10, "y": 20 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "first",
      "firstNotNull",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "체지방 녹이는 루틴 15븐 영상",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 11, "w": 5, "x": 15, "y": 20 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "first",
      "firstNotNull",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   }
  },
  { "title": "일별 기록 그래프", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "운동 데이터",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute as \"exercise\"\r\nFROM\r\n  exercise\r\nWHERE year in ($year) AND name in ($exercise_sort)\r\norder by year;"
    },
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute as \"home_exercise\"\r\nFROM\r\n  home_exercise\r\nWHERE year in ($year) AND name in ($exercise_sort)\r\norder by year;"
    }
   ]
  },
  {
   "title": "운동 데이터 | TimeSeries",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute as \"exercise\"\r\nFROM\r\n  exercise\r\nWHERE year in ($year) AND name in ($exercise_sort)\r\norder by year;"
    },
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute as \"home_exercise\"\r\nFROM\r\n  home_exercise\r\nWHERE year in ($year) AND name in ($exercise_sort)\r\norder by year;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n  year as s\n, year as e\n, name\n, minute\n, count_m\nFROM\nhome_exercise\n"
    }
   ]
  },
  {
   "title": " $exercise_sort  운동영상",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "rawSql": "select * from exercise_video\nwhere 1=1\n  and name in ( $exercise_sort )"
    }
   ]
  }
 ]
}