{
 "title": "kmp_대시보드",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   {
    "name": "year",
    "label": "날짜",
    "query": "select to_char(exercise.year, 'yyyy-mm-dd') as year from  exercise \nunion all\nselect to_char(home_exercise.year, 'yyyy-mm-dd')as year from  home_exercise\norder by year DESC\n;"
   },
   {
    "name": "exercise_sort",
    "label": "운동 종류(홈)",
    "query": "select name from home_exercise where year in ($year)\n union all\nselect name from exercise where year in ($year)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "운동 데이터",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute,\r\n  distance,\r\n  calories\r\nFROM\r\n  exercise\r\nWHERE year in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "$exercise_sort  Total Calories",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  calories\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "$exercise_sort  Total km",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  distance\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "운동 데이터",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  distinct name,\r\n  sum (minute) over(partition by name) as minute,\r\n  sum (distance) over(partition by name) as distance,\r\n  sum (calories) over(partition by name) as calories\r\nFROM\r\n  exercise\r\nWHERE year in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "총 운동 일 수",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(he.year))+count(distinct(e.year)) as Count from home_exercise he, exercise e;"
    }
   ]
  },
  {
   "title": "헬스장 운동 일 수",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(year)) as Count from exercise;"
    }
   ]
  },
  {
   "title": "$exercise_sort 헬스장 기록",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute,\r\n  distance,\r\n  calories\r\nFROM\r\n  exercise\r\nwhere year in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "home 운동 일 수",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(year)) as Count from home_exercise;"
    }
   ]
  },
  {
   "title": "home 운동 데이터",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute,\r\n  count_m\r\nFROM\r\n  home_exercise\r\nWHERE year in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "홈 트레이닝 $exercise_sort Total Minute(분)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  minute\r\nFROM\r\n home_exercise\r\nwhere 1=1\r\n  and year in ($year)\r\n  and name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "홈 트레이닝 $exercise_sort Total count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  count_m\r\nFROM\r\n  home_exercise\r\nwhere 1=1\r\n  and year in ($year)\r\n  and name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "home 운동 데이터",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n distinct\r\n  name,\r\n  sum (minute) over(partition by name) as minute,\r\n  sum (count_m) over(partition by name) as count_m\r\nFROM\r\n  home_exercise\r\nWHERE year in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "운동 데이터",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute as \"exercise\"\r\nFROM\r\n  exercise\r\nWHERE year in ($year) AND name in ($exercise_sort)\r\norder by year;"
    },
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute as \"home_exercise\"\r\nFROM\r\n  home_exercise\r\nWHERE year in ($year) AND name in ($exercise_sort)\r\norder by year;"
    }
   ]
  },
  {
   "title": "$exercise_sort 홈 트레이닝 기록",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year as \"Time\",\r\n  name,\r\n  minute\r\nFROM\r\n  exercise\r\nwhere year in ($year);"
    }
   ]
  }
 ]
}