{
 "title": "Algorithm",
 "time": { "from": "2021-07-02T03:00:00.000Z", "to": "2023-07-02T02:59:59.998Z" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select current_timestamp - '2022-07-08 00:00:00'\n-- 0709"
    }
   ]
  },
  {
   "title": "제일 마지막에 풀었던 문제",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nyear as \"time\"\n  ,problem_name\n  ,minute\nFROM\n  algorithm\norder by time\n-- WHERE\n--   $__timeFilter(year)\n"
    }
   ]
  },
  {
   "title": "algorithm Problem",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 11, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\nyear,\n  --$__time(year),\n  problem_name,\n  problem_number,\n  start_date,\n  end_date,\n  minute\nFROM\n  algorithm\n-- WHERE\n--   $__timeFilter(year)\n"
    }
   ]
  },
  {
   "title": "푸는 시간 히스토그램",
   "type": "histogram",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  problem_name,\n  minute\nFROM\n  algorithm\n-- WHERE\n--   $__timeFilter(year)\n"
    }
   ]
  },
  {
   "title": "algorithm Problem Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(problem_number) as count\nFROM\n  algorithm\n\n"
    }
   ]
  },
  {
   "title": "algorithm Problem  풀이시간 추이",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 2, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\nyear,\n  --$__time(year),\n  problem_name,\n  minute\nFROM\n  algorithm\n-- WHERE\n--   $__timeFilter(year)\n"
    }
   ]
  }
 ]
}