{
 "title": "confusion Metrix",
 "time": { "from": "2021-02-07T02:08:40.139Z", "to": "2023-02-07T02:08:40.139Z" },
 "panels": [
  {
   "title": "Case 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "infomation dri",
     "type": "table",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 1 },
     "targets": [
      { "rawSql": "select * from dri" }
     ]
    },
    {
     "title": "confusion metrix_v1.0.1 dri",
     "type": "table",
     "gridPos": { "h": 13, "w": 18, "x": 6, "y": 1 },
     "targets": [
      {
       "rawSql": "\r\nwith cm as(\r\nselect \r\n\tcase when reference_code = 1 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 1 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 1 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\twhen reference_code = 2 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 2 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 2 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\twhen reference_code = 3 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 3 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 3 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\twhen reference_code = 4 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 4 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 4 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n    when reference_code = 5 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 5 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 5 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n    when reference_code = 6 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 6 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 6 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\twhen reference_code = 7 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 7 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 7 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\twhen reference_code = 8 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 8 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 8 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\twhen reference_code = 9  and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 9 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 9 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n    when reference_code = 10 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 10 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 10 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\tend as D1\r\nfrom dri\r\n)\r\nselect \r\n(ROW_NUMBER() OVER()) as \" \",\r\nsplit_part(D1,',',1 )as \"1\"\r\n,split_part(D1,',',2 )as \"2\"\r\n,split_part(D1,',',3 )as \"3\"\r\n,split_part(D1,',',4 )as \"4\" \r\n,split_part(D1,',',5 )as \"5\"\r\n,split_part(D1,',',6 )as \"6\" \r\n,split_part(D1,',',7 )as \"7\" \r\n,split_part(D1,',',8 )as \"8\" \r\n,split_part(D1,',',9 )as \"9\" \r\n,split_part(D1,',',10 )as \"10\" \r\nfrom cm;"
      },
      {
       "rawSql": "\r\nwith cm as(\r\nselect \r\n\tcase when reference_code = 1 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =2 then '2,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =3 then '2,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =4 then '2,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =5 then '2,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =6 then '2,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =7 then '2,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =8 then '2,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 1 and  inference_code =9 then '2,0,0,0,0,0,0,0,1,0' \r\n\t\twhen reference_code = 1 and  inference_code =10 then '2,0,0,0,0,0,0,0,0,1'\r\n\t     when reference_code = 2 and  inference_code =1 then '1,2,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =3 then '0,2,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =4 then '0,2,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =5 then '0,2,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =6 then '0,2,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =7 then '0,2,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =8 then '0,2,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 2 and  inference_code =9 then '0,2,0,0,0,0,0,0,1,0' \r\n\t\twhen reference_code = 2 and  inference_code =10 then '0,2,0,0,0,0,0,0,0,1'\r\n\t     when reference_code = 3 and  inference_code =1 then '1,0,2,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =2 then '0,1,2,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =4 then '0,0,2,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =5 then '0,0,2,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =6 then '0,0,2,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =7 then '0,0,2,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =8 then '0,0,2,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 3 and  inference_code =9 then '0,0,2,0,0,0,0,0,1,0' \r\n\t\twhen reference_code = 3 and  inference_code =10 then '0,0,2,0,0,0,0,0,0,1'\r\n\t     when reference_code = 4 and  inference_code =1 then '1,0,0,2,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =2 then '0,1,0,2,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =3 then '0,0,1,2,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =5 then '0,0,0,2,1,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =6 then '0,0,0,2,0,1,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =7 then '0,0,0,2,0,0,1,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =8 then '0,0,0,2,0,0,0,1,0,0' \r\n\t\t when reference_code = 4 and  inference_code =9 then '0,0,0,2,0,0,0,0,1,0' \r\n\t\twhen reference_code = 4 and  inference_code =10 then '0,0,0,2,0,0,0,0,0,1'\r\n         when reference_code = 5 and  inference_code =1 then '1,0,0,0,2,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =2 then '0,1,0,0,2,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =3 then '0,0,1,0,2,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =4 then '0,0,0,1,2,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =6 then '0,0,0,0,2,1,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =7 then '0,0,0,0,2,0,1,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =8 then '0,0,0,0,2,0,0,1,0,0' \r\n\t\t when reference_code = 5 and  inference_code =9 then '0,0,0,0,2,0,0,0,1,0' \r\n\t\twhen reference_code = 5 and  inference_code =10 then '0,0,0,0,2,0,0,0,0,1'\r\n         when reference_code = 6 and  inference_code =1 then '1,0,0,0,0,2,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =2 then '0,1,0,0,0,2,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =3 then '0,0,1,0,0,2,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =4 then '0,0,0,1,0,2,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =5 then '0,0,0,0,1,2,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =7 then '0,0,0,0,0,2,1,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =8 then '0,0,0,0,0,2,0,1,0,0' \r\n\t\t when reference_code = 6 and  inference_code =9 then '0,0,0,0,0,2,0,0,1,0' \r\n\t\twhen reference_code = 6 and  inference_code =10 then '0,0,0,0,0,2,0,0,0,1'\r\n\t     when reference_code = 7 and  inference_code =1 then '1,0,0,0,0,0,2,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =2 then '0,1,0,0,0,0,2,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =3 then '0,0,1,0,0,0,2,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =4 then '0,0,0,1,0,0,2,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =5 then '0,0,0,0,1,0,2,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =6 then '0,0,0,0,0,1,2,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =8 then '0,0,0,0,0,0,2,1,0,0' \r\n\t\t when reference_code = 7 and  inference_code =9 then '0,0,0,0,0,0,2,0,1,0' \r\n\t    when reference_code = 7 and  inference_code =10 then '0,0,0,0,0,0,2,0,0,1'\r\n\t     when reference_code = 8 and  inference_code =1 then '1,0,0,0,0,0,0,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =2 then '0,1,0,0,0,0,0,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =3 then '0,0,1,0,0,0,0,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =4 then '0,0,0,1,0,0,0,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =5 then '0,0,0,0,1,0,0,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =6 then '0,0,0,0,0,1,0,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =7 then '0,0,0,0,0,0,1,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 8 and  inference_code =9 then '0,0,0,0,0,0,0,2,1,0' \r\n\t\twhen reference_code = 8 and  inference_code =10 then '0,0,0,0,0,0,0,2,0,1'\r\n\t     when reference_code = 9  and  inference_code=1 then '1,0,0,0,0,0,0,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =2 then '0,1,0,0,0,0,0,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =3 then '0,0,1,0,0,0,0,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =4 then '0,0,0,1,0,0,0,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =5 then '0,0,0,0,1,0,0,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =6 then '0,0,0,0,0,1,0,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =7 then '0,0,0,0,0,0,1,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =8 then '0,0,0,0,0,0,0,1,2,0' \r\n\t\t when reference_code = 9 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\twhen reference_code = 9 and  inference_code =10 then '0,0,0,0,0,0,0,0,2,1'\r\n         when reference_code = 10 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,2' \r\n\t\t when reference_code = 10 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,2' \r\n\t\twhen reference_code = 10 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\tend as D1\r\nfrom dri\r\n)\r\nselect \r\n(ROW_NUMBER() OVER()) as \" \",\r\nsplit_part(D1,',',1 )as \"1\"\r\n,split_part(D1,',',2 )as \"2\"\r\n,split_part(D1,',',3 )as \"3\"\r\n,split_part(D1,',',4 )as \"4\" \r\n,split_part(D1,',',5 )as \"5\"\r\n,split_part(D1,',',6 )as \"6\" \r\n,split_part(D1,',',7 )as \"7\" \r\n,split_part(D1,',',8 )as \"8\" \r\n,split_part(D1,',',9 )as \"9\" \r\n,split_part(D1,',',10 )as \"10\" \r\nfrom cm;"
      }
     ]
    }
   ]
  },
  {
   "title": "Case 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "infomation dri1",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 2 },
     "targets": [
      { "rawSql": "select * from dri1" }
     ]
    },
    {
     "title": "confusion metrix_v1.0.0 dri1",
     "type": "table",
     "gridPos": { "h": 12, "w": 18, "x": 6, "y": 2 },
     "targets": [
      {
       "rawSql": "\r\nwith cm as(\r\nselect \r\n\tcase when reference_code = 1 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 1 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 1 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\twhen reference_code = 2 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 2 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 2 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\twhen reference_code = 3 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 3 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 3 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\twhen reference_code = 4 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 4 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 4 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n    when reference_code = 5 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 5 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 5 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n    when reference_code = 6 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 6 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 6 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\twhen reference_code = 7 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 7 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 7 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\twhen reference_code = 8 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 8 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 8 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 8 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\twhen reference_code = 9  and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 9 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 9 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 9 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n    when reference_code = 10 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 10 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 10 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\t when reference_code = 10 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\tend as D1\r\nfrom dri1\r\n)\r\nselect \r\n(ROW_NUMBER() OVER()) as \" \",\r\nsplit_part(D1,',',1 )as \"1\"\r\n,split_part(D1,',',2 )as \"2\"\r\n,split_part(D1,',',3 )as \"3\"\r\n,split_part(D1,',',4 )as \"4\" \r\n,split_part(D1,',',5 )as \"5\"\r\n,split_part(D1,',',6 )as \"6\" \r\n,split_part(D1,',',7 )as \"7\" \r\n,split_part(D1,',',8 )as \"8\" \r\n,split_part(D1,',',9 )as \"9\" \r\n,split_part(D1,',',10 )as \"10\" \r\nfrom cm;"
      },
      {
       "rawSql": "\r\nwith cm as(\r\nselect \r\n\tcase when reference_code = 1 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =2 then '2,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =3 then '2,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =4 then '2,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =5 then '2,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =6 then '2,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =7 then '2,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 1 and  inference_code =8 then '2,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 1 and  inference_code =9 then '2,0,0,0,0,0,0,0,1,0' \r\n\t\twhen reference_code = 1 and  inference_code =10 then '2,0,0,0,0,0,0,0,0,1'\r\n\t     when reference_code = 2 and  inference_code =1 then '1,2,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =3 then '0,2,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =4 then '0,2,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =5 then '0,2,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =6 then '0,2,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =7 then '0,2,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 2 and  inference_code =8 then '0,2,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 2 and  inference_code =9 then '0,2,0,0,0,0,0,0,1,0' \r\n\t\twhen reference_code = 2 and  inference_code =10 then '0,2,0,0,0,0,0,0,0,1'\r\n\t     when reference_code = 3 and  inference_code =1 then '1,0,2,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =2 then '0,1,2,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =4 then '0,0,2,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =5 then '0,0,2,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =6 then '0,0,2,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =7 then '0,0,2,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 3 and  inference_code =8 then '0,0,2,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 3 and  inference_code =9 then '0,0,2,0,0,0,0,0,1,0' \r\n\t\twhen reference_code = 3 and  inference_code =10 then '0,0,2,0,0,0,0,0,0,1'\r\n\t     when reference_code = 4 and  inference_code =1 then '1,0,0,2,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =2 then '0,1,0,2,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =3 then '0,0,1,2,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =5 then '0,0,0,2,1,0,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =6 then '0,0,0,2,0,1,0,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =7 then '0,0,0,2,0,0,1,0,0,0' \r\n\t\t when reference_code = 4 and  inference_code =8 then '0,0,0,2,0,0,0,1,0,0' \r\n\t\t when reference_code = 4 and  inference_code =9 then '0,0,0,2,0,0,0,0,1,0' \r\n\t\twhen reference_code = 4 and  inference_code =10 then '0,0,0,2,0,0,0,0,0,1'\r\n         when reference_code = 5 and  inference_code =1 then '1,0,0,0,2,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =2 then '0,1,0,0,2,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =3 then '0,0,1,0,2,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =4 then '0,0,0,1,2,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =6 then '0,0,0,0,2,1,0,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =7 then '0,0,0,0,2,0,1,0,0,0' \r\n\t\t when reference_code = 5 and  inference_code =8 then '0,0,0,0,2,0,0,1,0,0' \r\n\t\t when reference_code = 5 and  inference_code =9 then '0,0,0,0,2,0,0,0,1,0' \r\n\t\twhen reference_code = 5 and  inference_code =10 then '0,0,0,0,2,0,0,0,0,1'\r\n         when reference_code = 6 and  inference_code =1 then '1,0,0,0,0,2,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =2 then '0,1,0,0,0,2,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =3 then '0,0,1,0,0,2,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =4 then '0,0,0,1,0,2,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =5 then '0,0,0,0,1,2,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =7 then '0,0,0,0,0,2,1,0,0,0' \r\n\t\t when reference_code = 6 and  inference_code =8 then '0,0,0,0,0,2,0,1,0,0' \r\n\t\t when reference_code = 6 and  inference_code =9 then '0,0,0,0,0,2,0,0,1,0' \r\n\t\twhen reference_code = 6 and  inference_code =10 then '0,0,0,0,0,2,0,0,0,1'\r\n\t     when reference_code = 7 and  inference_code =1 then '1,0,0,0,0,0,2,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =2 then '0,1,0,0,0,0,2,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =3 then '0,0,1,0,0,0,2,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =4 then '0,0,0,1,0,0,2,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =5 then '0,0,0,0,1,0,2,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =6 then '0,0,0,0,0,1,2,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,0' \r\n\t\t when reference_code = 7 and  inference_code =8 then '0,0,0,0,0,0,2,1,0,0' \r\n\t\t when reference_code = 7 and  inference_code =9 then '0,0,0,0,0,0,2,0,1,0' \r\n\t    when reference_code = 7 and  inference_code =10 then '0,0,0,0,0,0,2,0,0,1'\r\n\t     when reference_code = 8 and  inference_code =1 then '1,0,0,0,0,0,0,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =2 then '0,1,0,0,0,0,0,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =3 then '0,0,1,0,0,0,0,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =4 then '0,0,0,1,0,0,0,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =5 then '0,0,0,0,1,0,0,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =6 then '0,0,0,0,0,1,0,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =7 then '0,0,0,0,0,0,1,2,0,0' \r\n\t\t when reference_code = 8 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,0' \r\n\t\t when reference_code = 8 and  inference_code =9 then '0,0,0,0,0,0,0,2,1,0' \r\n\t\twhen reference_code = 8 and  inference_code =10 then '0,0,0,0,0,0,0,2,0,1'\r\n\t     when reference_code = 9  and  inference_code=1 then '1,0,0,0,0,0,0,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =2 then '0,1,0,0,0,0,0,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =3 then '0,0,1,0,0,0,0,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =4 then '0,0,0,1,0,0,0,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =5 then '0,0,0,0,1,0,0,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =6 then '0,0,0,0,0,1,0,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =7 then '0,0,0,0,0,0,1,0,2,0' \r\n\t\t when reference_code = 9 and  inference_code =8 then '0,0,0,0,0,0,0,1,2,0' \r\n\t\t when reference_code = 9 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,0' \r\n\t\twhen reference_code = 9 and  inference_code =10 then '0,0,0,0,0,0,0,0,2,1'\r\n         when reference_code = 10 and  inference_code =1 then '1,0,0,0,0,0,0,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =2 then '0,1,0,0,0,0,0,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =3 then '0,0,1,0,0,0,0,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =4 then '0,0,0,1,0,0,0,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =5 then '0,0,0,0,1,0,0,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =6 then '0,0,0,0,0,1,0,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =7 then '0,0,0,0,0,0,1,0,0,2' \r\n\t\t when reference_code = 10 and  inference_code =8 then '0,0,0,0,0,0,0,1,0,2' \r\n\t\t when reference_code = 10 and  inference_code =9 then '0,0,0,0,0,0,0,0,1,2' \r\n\t\twhen reference_code = 10 and  inference_code =10 then '0,0,0,0,0,0,0,0,0,1'\r\n\tend as D1\r\nfrom dri1\r\n)\r\nselect \r\n(ROW_NUMBER() OVER()) as \" \",\r\nsplit_part(D1,',',1 )as \"1\"\r\n,split_part(D1,',',2 )as \"2\"\r\n,split_part(D1,',',3 )as \"3\"\r\n,split_part(D1,',',4 )as \"4\" \r\n,split_part(D1,',',5 )as \"5\"\r\n,split_part(D1,',',6 )as \"6\" \r\n,split_part(D1,',',7 )as \"7\" \r\n,split_part(D1,',',8 )as \"8\" \r\n,split_part(D1,',',9 )as \"9\" \r\n,split_part(D1,',',10 )as \"10\" \r\nfrom cm;"
      }
     ]
    }
   ]
  },
  {
   "title": "Case 3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "infomation dri1",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 3 },
     "targets": [
      { "rawSql": "select * from dri1" }
     ]
    },
    {
     "title": "confusion metrix_v1.0.1 dri  pl/sql",
     "type": "table",
     "gridPos": { "h": 12, "w": 18, "x": 6, "y": 3 },
     "targets": [
      {
       "rawSql": "select fn_test_table_insert();\r\n\r\n"
      },
      { "rawSql": "select * from public.test2;" }
     ]
    }
   ]
  },
  {
   "title": "Case4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "infomation ep",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 4 },
     "targets": [
      { "rawSql": "select * from ep" }
     ]
    },
    {
     "title": "infomation ep",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 4 },
     "targets": [
      {
       "rawSql": "\r\nwith eps as(\r\nselect distinct Expected, predicted, count(predicted) over(partition by Expected,predicted)as cnt  from ep order by expected, predicted \r\n), eps1 as(\r\nselect expected, predicted, round((cnt/sum(cnt) over(partition by Expected)),2)::text as percent from eps)\r\nselect * from eps1"
      }
     ]
    },
    {
     "title": "confusion metrix_v1.0.1 dri  pl/sql",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "rawSql": "select fn_test_table_insert1();\r\n\r\n"
      },
      { "rawSql": "select * from public.test4;" }
     ]
    }
   ]
  }
 ]
}