{
 "title": "Grafana Study_backup",
 "time": { "from": "now-7y/y", "to": "now" },
 "templating": {
  "list": [
   { "name": "sitename", "label": "사이트", "query": "select name from table_time ;" }
  ]
 },
 "panels": [
  {
   "title": "time series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n\t\t$__timeFrom() as from\n\t\t,$__timeTo() as to\n;"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "rawSql": "select study_time as time,\nname, \ncount,\nmoney\nfrom kmp2\norder by time"
      },
      {
       "rawSql": "select study_time as time,\nname, \ncount,\nmoney\nfrom kmp2\norder by time"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "select study_time as time,\nname, \ncount\nfrom kmp1\norder by time"
      }
     ]
    },
    {
     "title": "두개이상을 가지는 데이터 그래프",
     "type": "timeseries",
     "description": "그래프에 대한 설명",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "select study_time as time,\nname, \ncount,\nmoney\nfrom kmp2\norder by time"
      }
     ]
    }
   ]
  },
  {
   "title": "bar chart",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\ncategory,\nsum (count(title)) over(partition by category) as sum\nFROM mse1\ngroup by title, category\nunion\nselect null, null\norder by sum nulls last\n\n\n"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\ncategory,\nsum (count(title)) over(partition by category) as sum\nFROM mse1\ngroup by title, category\nunion\nselect null, null\norder by sum nulls last\n\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "Select dates as time , url, name  from table_time "
      },
      { "rawSql": "Select * from exercise; " }
     ]
    }
   ]
  },
  {
   "title": "Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(sale_date)\n  ,car_name  \n  ,car_money\n  ,option_money\nFROM carShop\norder by sale_date asc\n\n\n"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(sale_date)\n  ,car_name\n  ,car_money\n  ,option_money\nFROM carShop\n\n\n"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(sale_date)\n  ,car_name\n  ,car_money\n  ,option_money\nFROM carShop\n\n\n"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(sale_date)\n  ,car_name\n  ,car_money \n  ,option_money\nFROM carShop"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(sale_date)\n  ,car_name\n  ,car_money\n  ,option_money\nFROM carShop\nwhere car_name in ('투싼');\n\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Heat Map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(sale_date)\n  ,car_name\n  ,car_money as \" \"\n -- ,option_money\nFROM carShop \n"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(sale_date)\n  ,car_name\n  ,car_money as \" \"\n -- ,option_money\nFROM carShop \n"
      }
     ]
    }
   ]
  },
  {
   "title": "Gant Chart",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "아이폰 출시 및 단종시간",
     "type": "marcusolsson-gantt-panel",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 6 },
     "targets": [
      { "rawSql": "SELECT \n*\nFROM\n  iphone" }
     ]
    },
    {
     "title": "Group by Model",
     "type": "marcusolsson-gantt-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      { "rawSql": "SELECT \n*\nFROM\n  iphone" }
     ]
    },
    {
     "title": "Group by Model",
     "type": "marcusolsson-gantt-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      { "rawSql": "SELECT \n*\nFROM\n  iphone" }
     ]
    }
   ]
  },
  {
   "title": "Iframe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "지도",
     "type": "gapit-htmlgraphics-panel",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 7 },
     "options": {
      "reduceOptions": {
       "calcs": [
        "lastNotNull",
        "last",
        "first",
        "firstNotNull",
        "min",
        "max",
        "mean",
        "sum",
        "count",
        "range",
        "delta",
        "step",
        "diff",
        "logmin",
        "allIsZero",
        "allIsNull",
        "diffperc"
       ]
      }
     }
    },
    {
     "title": "내 블로그 ",
     "type": "gapit-htmlgraphics-panel",
     "gridPos": { "h": 16, "w": 10, "x": 7, "y": 7 },
     "options": {
      "reduceOptions": {
       "calcs": [
        "lastNotNull",
        "last",
        "first",
        "firstNotNull",
        "min",
        "max",
        "mean",
        "sum",
        "count",
        "range",
        "delta",
        "step",
        "diff",
        "logmin",
        "allIsZero",
        "allIsNull",
        "diffperc"
       ]
      }
     }
    },
    {
     "title": "동영상  재생",
     "type": "gapit-htmlgraphics-panel",
     "gridPos": { "h": 16, "w": 7, "x": 17, "y": 7 },
     "options": {
      "reduceOptions": {
       "calcs": [
        "lastNotNull",
        "last",
        "first",
        "firstNotNull",
        "min",
        "max",
        "mean",
        "sum",
        "count",
        "range",
        "delta",
        "step",
        "diff",
        "logmin",
        "allIsZero",
        "allIsNull",
        "diffperc"
       ]
      }
     }
    }
   ]
  },
  {
   "title": "Stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Value TimeSeries",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select $__time(release_date), model_name, first_cost \" \" from iphone"
      }
     ]
    },
    {
     "title": "Last Value Table",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select $__time(release_date), model_name, first_cost \" \" from iphone"
      }
     ]
    },
    {
     "title": "First Value",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      { "rawSql": "select * from iphone" }
     ]
    },
    {
     "title": "Last Value",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "rawSql": "select * from iphone" }
     ]
    }
   ]
  },
  {
   "title": "Gauage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "First",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "rawSql": "SELECT\nrelease_date as \"time\"\n, model_name \n, first_cost\nFROM\niphone"
      }
     ]
    },
    {
     "title": "Last",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\nrelease_date as \"time\"\n, model_name \n, first_cost\nFROM\niphone"
      }
     ]
    }
   ]
  },
  {
   "title": "Bar Gauage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "First",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "rawSql": "SELECT\nrelease_date as \"time\"\n, model_name \n, first_cost\nFROM\niphone"
      }
     ]
    },
    {
     "title": "First",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "rawSql": "SELECT\nrelease_date as \"time\"\n, model_name \n, first_cost\nFROM\niphone"
      }
     ]
    }
   ]
  },
  {
   "title": "Pie Chart",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(sale_date)\n, car_name as \" \"\n, car_money as \"  \"\nFROM\n  carShop\nwhere 1=1\n  and ($__timeFrom() <= sale_date or sale_date <= $__timeTo() );"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(sale_date)\n, car_name as \" \"\n, car_money as \"  \"\n, option_money as \"   \"\nFROM\n  carShop\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  car_name as \" \",\n  car_money as \"  \"\nFROM\n  carShop"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(sale_date),\n  car_name as \" \",\n  car_money as \"  \"\nFROM\n  carShop"
      }
     ]
    }
   ]
  }
 ]
}