{
 "title": "Lotto",
 "time": { "from": "2002-11-18T00:03:22.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "year",
    "label": "년도",
    "query": "SELECT TO_CHAR(drwNoDate,'YYYY-MM-DD') as year FROM lotto ORDER BY year desc"
   }
  ]
 },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 } },
  {
   "title": "회차",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  drwNoDate as time,\r\n  drwNo\r\n  --firstPrzwnerCo as \"1등 당첨자 수\"\r\n  --firstWinamnt as \"당처 금액\"\r\n  -- drwtNo1,\r\n  -- drwtNo2,\r\n  -- drwtNo3,\r\n  -- drwtNo4,\r\n  -- drwtNo5,\r\n  -- drwtNo6,\r\n  -- bnusNo\r\nFROM\r\n  lotto\r\nunion all\r\nselect null ,null\r\norder by time nulls first\r\n--WHERE Time in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "최근 1등 당첨자(명)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n drwNoDate as time, \r\n  --drwNo,\r\n  firstPrzwnerCo as \"1등 당첨자 수\"\r\n  --firstWinamnt\r\n  -- drwtNo1,\r\n  -- drwtNo2,\r\n  -- drwtNo3,\r\n  -- drwtNo4,\r\n  -- drwtNo5,\r\n  -- drwtNo6,\r\n  -- bnusNo\r\nFROM\r\n  lotto\r\n  \r\n  union all\r\nselect null ,null\r\norder by time nulls first\r\n--WHERE Time in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "최근1등 금액",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  drwNoDate as time,\r\n  --drwNo,\r\n  --firstPrzwnerCo as \"1등 당첨자 수\"\r\n  firstWinamnt as \"당처 금액\"\r\n  -- drwtNo1,\r\n  -- drwtNo2,\r\n  -- drwtNo3,\r\n  -- drwtNo4,\r\n  -- drwtNo5,\r\n  -- drwtNo6,\r\n  -- bnusNo\r\nFROM\r\n  lotto\r\nunion all\r\nselect null ,null\r\norder by time nulls first\r\n--WHERE Time in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "로또 1등 번호",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  drwNoDate as \"Time\",\r\n   drwtNo1 as \"NO1\",\r\n   drwtNo2 as \"NO2\",\r\n   drwtNo3 as \"NO3\",\r\n   drwtNo4 as \"NO4\",\r\n   drwtNo5 as \"NO5\",\r\n   drwtNo6 as \"NO6\",\r\n   bnusNo as \"보너스\"\r\nFROM\r\n  lotto\r\nORDER BY drwnoDate desc\r\n--WHERE Time in ($year) AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "로또 1등 금액 추이",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  drwNoDate as time,\r\n  --drwNo,\r\n  --firstPrzwnerCo,\r\n  firstWinamnt as \"당첨금액\"\r\n  -- drwtNo1,\r\n  -- drwtNo2,\r\n  -- drwtNo3,\r\n  -- drwtNo4,\r\n  -- drwtNo5,\r\n  -- drwtNo6,\r\n  -- bnusNo\r\nFROM\r\n  lotto\r\nWHERE drwNoDate in ($year)\r\nunion all\r\nselect null ,null\r\norder by time nulls first\r\n--AND name in ($exercise_sort);"
    }
   ]
  },
  {
   "title": "로또 1등 당첨자 추이",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  drwNoDate as time,\r\n  --drwNo,\r\n  firstPrzwnerCo as \"1등 당첨자 수\"\r\n  --firstWinamnt\r\n  -- drwtNo1,\r\n  -- drwtNo2,\r\n  -- drwtNo3,\r\n  -- drwtNo4,\r\n  -- drwtNo5,\r\n  -- drwtNo6,\r\n  -- bnusNo\r\nFROM\r\n  lotto\r\nWHERE drwNoDate in ($year)\r\nunion all\r\nselect null ,null\r\norder by time nulls first"
    }
   ]
  },
  {
   "title": "로또 1등 번호 테이블",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  drwNoDate as \"Time\",\r\n  drwNo as \"회차\",\r\n  firstPrzwnerCo as \"1등 당첨자 (명)\",\r\n  firstWinamnt as \"1등 당첨 금액 (원)\",\r\n   drwtNo1 as \"NO1\",\r\n   drwtNo2 as \"NO2\",\r\n   drwtNo3 as \"NO3\",\r\n   drwtNo4 as \"NO4\",\r\n   drwtNo5 as \"NO5\",\r\n   drwtNo6 as \"NO6\",\r\n   bnusNo as \"보너스\"\r\nFROM\r\n  lotto\r\nORDER BY drwnoDate desc\r\n--WHERE Time in ($year) AND name in ($exercise_sort);"
    }
   ]
  }
 ]
}